### ISSUE TITLE
HibernateSystemException on Review page

### ISSUE THREAD

**Issue by jmvezic** [DIA-NZ/webcurator#141]
Upon stopping a harvest that was stuck on a few resources (trying to collect them every hour), the harvest was successfully put into "Harvested" state, but the Review link in the harvest results gives the error:

```
An unexpected error occured
--
org.springframework.orm.hibernate3.HibernateSystemException: query did not return a unique result: 2; 
nested exception is org.hibernate.NonUniqueResultException: query did not return a unique result: 2
```

catalina.out shows:
```
2021-06-15 09:22:08,552 ERROR [http-nio-8080-exec-9] layouts.Error_jsp (Error_jsp.java:136) - The error page detected an unexpected error: org.springframework.orm.hibernate3.HibernateSystemException: query did not return a unique result: 2; nested exception is org.hibernate.NonUniqueResultException: query did not return a unique result: 2
org.springframework.orm.hibernate3.HibernateSystemException: query did not return a unique result: 2; nested exception is org.hibernate.NonUniqueResultException: query did not return a unique result: 2
org.hibernate.NonUniqueResultException: query did not return a unique result: 2
        at org.hibernate.impl.AbstractQueryImpl.uniqueElement(AbstractQueryImpl.java:762)
        at org.hibernate.impl.AbstractQueryImpl.uniqueResult(AbstractQueryImpl.java:749)
        at org.webcurator.domain.TargetInstanceDAOImpl$8.doInHibernate(TargetInstanceDAOImpl.java:282)
        at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:366)
        at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:334)
        at org.webcurator.domain.TargetInstanceDAOImpl.getHarvestResourceDTO(TargetInstanceDAOImpl.java:277)
        at org.webcurator.ui.tools.controller.QualityReviewToolController.load(QualityReviewToolController.java:167)
        at org.webcurator.ui.tools.controller.QualityReviewToolController.handle(QualityReviewToolController.java:138)
        at org.springframework.web.servlet.mvc.AbstractCommandController.handleRequestInternal(AbstractCommandController.java:81)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:44)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:723)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:663)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:394)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:348)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:264)
        at org.webcurator.auth.dbms.WCTForcePasswordChange.doFilter(WCTForcePasswordChange.java:94)
        at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:274)
        at org.acegisecurity.intercept.web.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:107)
        at org.acegisecurity.intercept.web.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:72)
        at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:274)
        at org.acegisecurity.ui.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:110)
        at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:274)
        at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:217)
        at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:274)
        at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:191)
        at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:274)
        at org.acegisecurity.util.FilterChainProxy.doFilter(FilterChainProxy.java:148)
        at org.acegisecurity.util.FilterToBeanProxy.doFilter(FilterToBeanProxy.java:90)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:75)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by schmika** [comment]
I think I remember a similar error message: for us, it was due to the fact that two URLs in the seed list actually referred to the same resource (requests for an older http URL were forwarded to an https URL that was also part of the seed list).
Maybe you would like to check your seed list for hidden duplicates?

**Comment by jmvezic** [comment]
@schmika no duplicates, it seems

**Comment by jmvezic** [comment]
@schmika no duplicates in initial seeds list, but it seems there are duplicates for the harvest result in URLs in database. A bunch of them are actually a different case, but there are actual duplicates , mostly robots.txt URLs from sites. How did you resolve this issue on your end?

**Comment by schmika** [comment]
In our case it was just a matter of cleaning up the seed list and removing the older http URL. As far as I know, we haven't had duplicates for the harvest results afterwards.
I'm sorry I couldn't be of more help!

**Comment by jmvezic** [comment]
You mean from the database itself after the harvest was done or from the initial seed list?

**Comment by schmika** [comment]
We rejected the initial harvest, updated the seed list and started a new crawl. We didn't manually remove harvest resources from the database.

**Comment by jmvezic** [comment]
@schmika Thanks for the details, it turns out there were in fact duplicates in seeds list, more specifically, one seed had a redirect to another seed.
