### ISSUE TITLE
Can't review harvest - NonUniqueResultException

### ISSUE THREAD

**Issue by obrienben** [DIA-NZ/webcurator#5]
Occasionally an error can occur with a new harvest, the review screen is blocked by a Hibernate error

```
org.hibernate.NonUniqueResultException: query did not return a unique result: 2
        at org.hibernate.impl.AbstractQueryImpl.uniqueElement(AbstractQueryImpl.java:762)
        at org.hibernate.impl.AbstractQueryImpl.uniqueResult(AbstractQueryImpl.java:749)
        at org.webcurator.domain.TargetInstanceDAOImpl$8.doInHibernate(TargetInstanceDAOImpl.java:280)
        at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:366)
        at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:334)
        at org.webcurator.domain.TargetInstanceDAOImpl.getHarvestResourceDTO(TargetInstanceDAOImpl.java:275)
        at org.webcurator.ui.tools.controller.QualityReviewToolController.load(QualityReviewToolController.java:132)
        at org.webcurator.ui.tools.controller.QualityReviewToolController.handle(QualityReviewToolController.java:99)
```

Inside the Harvest_Resource table there will be a duplicate seed URL for this Target Instance. How this occurs is still not known.
A quick fix is to un-link the Harvest_Resource row to its corresponding Harvest_Result, so that it is not returned in the Hibernate query above. The HRC_HARVEST_RESULT_OID column can be set to a something that doesn't conflict with another Harvest Result.

**Comment by bitzl** [comment]
I've observed a (probably) similar behavior in our systems. Seems that this error occurs if the seed URL has a redirect, e.g.

    http://www.example.com --> http://www.example.com/index.php
