### ISSUE TITLE
production heritrix 1 agent has classpath conflict with commons-httpclient

### ISSUE THREAD

**Issue by kurtlenfesty** [DIA-NZ/webcurator#97]
This is with the `replace-jboss-soap-with-latest-jaxws-rt` branch running in production.

The exception in the logs is as follows:
```
2019-01-31 21:15:07,730 INFO  [http-nio-8080-exec-7] agent.HarvesterHeritrix (HarvesterHeritrix.java:447) - Found and initialised job 105873691
Jan 31, 2019 9:15:07 PM org.archive.crawler.admin.CrawlJob postRegister
INFO: org.archive.crawler:host=kaiwae-z4,mother=105873691,name=105873691-20190131081507687,type=CrawlService.Job registered to MBeanServerId=kaiwae-z4_1548909441867, SpecificationVersion=1.4, ImplementationVersion=1.8.0_112-b15, SpecificationVendor=Oracle Corporation
Exception in thread "StartNextJob" java.lang.NoSuchMethodError: org.apache.commons.httpclient.HttpState.setCookiesMap(Ljava/util/SortedMap;)V
        at org.archive.crawler.fetcher.FetchHTTP.configureHttpCookies(FetchHTTP.java:1269)
        at org.archive.crawler.fetcher.FetchHTTP.configureHttp(FetchHTTP.java:1226)
        at org.archive.crawler.fetcher.FetchHTTP.initialTasks(FetchHTTP.java:1160)
        at org.archive.crawler.framework.CrawlController.runProcessorInitialTasks(CrawlController.java:1661)
        at org.archive.crawler.framework.CrawlController.requestCrawlStart(CrawlController.java:1006)
        at org.archive.crawler.admin.CrawlJobHandler.startNextJobInternal(CrawlJobHandler.java:1148)
        at org.archive.crawler.admin.CrawlJobHandler$3.run(CrawlJobHandler.java:1125)
        at java.lang.Thread.run(Thread.java:745)
```

It appears that the classloader is loading the HttpState found in commons-httpclient-3.1.jar instead of the HttpState found in aheritrix-1.14.1.jar.

This classloader issue has probably surfaced due to the change in dependencies as part of the jaxws-rt changes.

**Comment by kurtlenfesty** [comment]
Resolved by https://github.com/DIA-NZ/webcurator/pull/98
